# Generated by Django 4.1.7 on 2023-04-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_faq_rename_name_services_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'db_table': 'gallary',
            },
        ),
    ]
