# Generated by Django 4.1.7 on 2023-04-18 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('vehicletype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 18)),
        ),
    ]
